spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/ms_users_dev
  liquibase:
    change-log: liquibase/changelog-master.yaml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
