server:
  port:
    8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/ms_users_dev
  liquibase:
    change-log: liquibase/changelog-master.yaml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

client:
  urls:
    ms-account: http://localhost:8080/api/v1/accounts
